services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'cities_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

volumes:
  my-db: